version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: warehouse-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: warehouse
      MYSQL_USER: wh_user
      MYSQL_PASSWORD: wh_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_network

volumes:
  mysql_data:

networks:
  app_network:
    driver: bridge